export const FETCH_STANDINGS = 'FETCH_STANDINGS';
export const GET_STANDINGS_REQUEST = 'GET_STANDINGS_REQUEST';
export const GET_STANDINGS_SUCCESS = 'GET_STANDINGS_SUCCESS';
export const GET_STANDINGS_FAILURE = 'GET_STANDINGS_FAILURE';

export const FETCH_BOOKMAKERS = 'FETCH_BOOKMAKERS';
export const GET_BOOKMAKERS_REQUEST = 'GET_BOOKMAKERS_REQUEST';
export const GET_BOOKMAKERS_SUCCESS = 'GET_BOOKMAKERS_SUCCESS';
export const GET_BOOKMAKERS_FAILURE = 'GET_BOOKMAKERS_FAILURE';

export const FETCH_BOOKMAKER_INFO = 'FETCH_BOOKMAKER_INFO';
export const GET_BOOKMAKER_INFO_REQUEST = 'GET_BOOKMAKER_INFO_REQUEST';
export const GET_BOOKMAKER_INFO_SUCCESS = 'GET_BOOKMAKER_INFO_SUCCESS';
export const GET_BOOKMAKER_INFO_FAILURE = 'GET_BOOKMAKER_INFO_FAILURE';

export const FETCH_FIXTURES = 'FETCH_FIXTURES';
export const GET_FIXTURES_REQUEST = 'GET_FIXTURES_REQUEST';
export const GET_FIXTURES_SUCCESS = 'GET_FIXTURES_SUCCESS';
export const GET_FIXTURES_FAILURE = 'GET_FIXTURES_FAILURE';

export const FETCH_FIXTURES_LIVE = 'FETCH_FIXTURES_LIVE';
export const GET_FIXTURES_LIVE_REQUEST = 'GET_FIXTURES_LIVE_REQUEST';
export const GET_FIXTURES_LIVE_SUCCESS = 'GET_FIXTURES_LIVE_SUCCESS';
export const GET_FIXTURES_LIVE_FAILURE = 'GET_FIXTURES_LIVE_FAILURE';

export const FETCH_FIXTURES_LIVE_PREMIER_LEAGUE = 'FETCH_FIXTURES_LIVE_PREMIER_LEAGUE';

export const FETCH_TEAM = 'FETCH_TEAM';
export const GET_TEAM_REQUEST = 'GET_TEAM_REQUEST';
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS';
export const GET_TEAM_FAILURE = 'GET_TEAM_FAILURE';

export const FETCH_TEAMS = 'FETCH_TEAMS';
export const GET_TEAMS_REQUEST = 'GET_TEAMS_REQUEST';
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const GET_TEAMS_FAILURE = 'GET_TEAMS_FAILURE';
